- python/readme.md
- python/turtle-design.py
It creates design with help of python turtle library.
> Design with Turtle Library.

- DSA/C/deque.c
> Added deque.c

- DSA_python/README.md
- DSA_python/stack.py
I wrote a Python stack Code as you mentioned with a readme file where I mentioned Time complexity.
Please do check it and please merge it
> DSA Python Codes

- WebDev Projects/Analog Watch/index.html
- WebDev Projects/background-color-changer/index.html
- WebDev Projects/background-color-changer/script.js
- WebDev Projects/background-color-changer/style.css
please add this under hacktoberfest 2021
> analog clock

- DSA/C++/checkLeapYear.cpp
Created a C++ folder and added a leap year program in it.
> added leap year program in C++

- WebDev Projects/Simple Landing Page/index.html
- WebDev Projects/Simple Landing Page/styles.css
> add my simple landing page

- WebDev Projects/snake game/Snake_Game.html
Added a new snake game.Hope u like it .please accept my PR
> Added Snake game

- python/readme.md
- python/xc_to_m3u.py
> Added XC to M3U converter

- .gitignore
- DSA/Java/BinarySearch.java
- DSA/Java/readme.md
> Binary Search Algorithm

- DSA/C++/odd_even.cpp
this code tells us whether a number is odd or even using bitwise AND operator.
> added code for odd_even.cpp

- DSA/C++/bubble_sort.cpp
This program modifies the original array, and do not consume any extra space.
Time Complexity: O(n^2).
Space Complexity: O(1).
> inplace bubble sort.cpp

- DSA/C++/set_bits.cpp
this program is used to count the number of set bits in n.
Time Complexity: O(k). where k is the number of set bits in number n.
Space Complexity: O(1).
> added set_bits.cpp to count set bits

- Other Projects/Solar System Simulation/readme.md
Added a folder for other projects not based on Python and common coding languages and added a project : Solar System Simulation made with Unity Game Engine by Arush Mangal. #33
> Added Solar System Simulation

- DSA/C++/DSU.cpp
Complete code for disjoint subset union added using C++.
> DSU code added

- DSA/C++/bits_flip.cpp
Count number of bits to be flipped to convert A into B
Time Complexity: O( logn ).
Space Complexity: O(1).
> added bits_flip.cpp

- DSA/C++/avl.cpp
Complete implementation of AVL tree using C++
> avl_tree_code_added

- DSA/Java/print_KPC.java
please accept it under Hacktoberfest'21.
> Added a java dsa problem

- python/url_shortner.py
Created a URL Shortener using Python using tinyurl api
> Added url shortner script

- DSA_python/Mini-Max Sum/readme.md
- DSA_python/Mini-Max Sum/solution.py
- DSA_python/README.md
- DSA_python/Write a Function/readme.md
- DSA_python/Write a Function/solution.py
- python/OlympicsLogo.py
- python/readme.md
Updated:-
1. 'README.md' in DSA_Python
2. Added 2 DSA Problems and Solutions
3. 'README.md' in python
4. Added Python code to make olympics logo using turtle
#3
> Added 2 DSA Problems and Code to make olympics logo

- DSA/C++/Quick Sort
This is my code for Quick Sort, here I have explained how to perform quick sort and also told about various time complexities.
> Create Quick Sort

- DSA/C++/insertion sort.cpp
insertion sort algorithm explained.
> Insertion Sort Algorithm

- DSA/C++/Counting_sort.cpp
Counting sort is a sorting technique based on keys between a specific range. It works by counting the number of objects having distinct key values (kind of hashing).
> Counting_Sort_DSA

- DSA/JavaScript/binary_search_tree.js
- DSA/JavaScript/readme.md
Things covered in this pr: #4 
Added a JavaScript class for Binary Search Tree which provides following functionality:
- Create ( create instance of Binary Search Tree )
- Insert
- Delete
- Includes
- Number of nodes
- Is valid BST
- Display
- Traversals ( in-order, pre-order, post-order )
> :sparkles: Added binary search tree javascript class

- python/WebsiteAvailabilityChecker.py
- python/readme.md
It checks the availability of a website from python.
> Created Website Availability Checker

- WebDev Projects/ScoreKeeper/scoreKeeper.html
- WebDev Projects/ScoreKeeper/scoreKeeper.js
I have added a Score Keeper small project programmed in vanilla JavaScript!. Happy Contributing!
> added a Score Keeper game programmed in javascript

- WebDev Projects/JS calculator/indexhtml.html
- WebDev Projects/JS calculator/script.js
- WebDev Projects/JS calculator/styles.css
I have added a calculator using JavaScript, CSS and HTML ! Happy Contributing!
> added a Calculator programmed using Vanila JS,html and css.

- MLProjects/Titanic/Titanic_Gaurang.ipynb
- MLProjects/Titanic/titanic.csv
> Added ML Titanic project

- python/Dictionary_Definition.py
- python/readme.md
It checks the definitions of words available in the list using the dictionary.com website.
> Created the dictionary definition checker.

- DSA/C++/Kadane's Algo.cpp
Problem Statement:
Write an efficient program to find the sum of contiguous subarray within a one-dimensional array of numbers that has the largest sum. 
Explanation:
The simple idea of Kadane’s algorithm is to look for all positive contiguous segments of the array (max_ending_here is used for this). And keep track of maximum sum contiguous segment among all positive segments (max_so_far is used for this). Each time we get a positive-sum compare it with max_so_far and update max_so_far if it is greater than max_so_far
> Kadane's Alogrithm in cpp

- WebDev Projects/Digital_Clock/index.html
- WebDev Projects/Digital_Clock/scripts.js
- WebDev Projects/Digital_Clock/styles.css
I have added a project of Digital Clock using HTML, CSS and JS
Related Issue #115
> Added Digital Clock in Webdev Projects

- DSA/Python/insertion_sort.py
> Added a program - to implement insertion sort using array in python

- python/Stop Watch
Stop Watch using basic python.
>  Stop Watch

- python/Digital_Clock_with_python.py
Made a digital clock using intermediate Python
> Digital_Clock_with_Python

- python/Print Floyd Triangle
> Create Print Floyd Triangle
